# name: sAndP-check-yahoo-finance

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '37 22 * * 1-5' # runs once every weekday at 4:37 pm EST (after market close)

# jobs:
#   build:
#     runs-on: ubuntu-20.04
#     steps:

#       - name: checkout repo content
#         uses: actions/checkout@v3 # checkout the repository content to github runner

#       - name: setup python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10.1' # install the python version needed
          
#       - name: install python packages
#         run: |
#           python -m pip install --upgrade pip
#           pip install pipenv
#           pipenv install
          
#       - name: execute py script 
#         run: pipenv run python sAndPCheck.py
#         env: 
#           SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
#           RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL}}
#           EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        
          
#       - name: commit & push files
#         run: |
#           git pull
#           git config --local user.email "actions@users.noreply.github.com"
#           git config --local user.name "Automated"
#           git add -A
#           timestamp=$(date -u)
#           git commit -m "Latest S and P check: ${timestamp}" || exit 0
#           git push
